name: Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: Run test - Ubuntu ${{ matrix.ubuntu-version }}
    runs-on: ubuntu-${{ matrix.ubuntu-version }}
    strategy:
      matrix:
        ubuntu-version: ["25.04"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update --quiet
          sudo apt-get install --yes \
                desktop-file-utils \
                intltool \
                libayatana-appindicator3-dev \
                libglib2.0-dev \
                libgtk-3-dev \
                libpeas-dev \
                libunity-dev \
                libxtst-dev \
                libzeitgeist-2.0-dev \
                meson \
                valac \
                xvfb at-spi2-core
      - name: Build & Test
        run: meson builddir && ninja -C builddir test
